[book]
authors = ["Cardinal Cryptography"]
language = "en"
description = "Documentation of the rust implementation of Bankless protocol"
multilingual = false
src = "docs/src"
title = "BanklessBFT"

[build]
build-dir = "docs/book"
create-missing = false
